groonga/packages.groonga.org

- ansible/files/home/packages/bin/create-snapshot-package.sh
5.6.29 had been deleted in jaist mirror.
> Bump up using mysql source version to 5.6.40

- sentencepiece/debian/rules
Without this commit, it causes build error.
(install path doesn't match)
> sentencepiece: set -DCMAKE_INSTALL_LIBDIR= for Ubuntu 18.04

- mecab/Rakefile
Sources are moved from `https://repo.almalinux.org/almalinux/...`  to `https://repo.almalinux.org/vault...`.
> mecab: update source url

- Gemfile
Without this fix, it causes the following LoadError:
% rake -T
rake aborted!
LoadError: cannot load such file -- apt-dists-merge
> Install apt-dists-merge explicitly

- groonga-release/Rakefile
- groonga-release/yum/groonga-release.spec.in
- groonga-release/yum/oracle-linux-8/Dockerfile
We will provide package for Oracle Linux 8.
Mroonga for AlmaLinux 8 required mysql-community-server. However, MySQL official Docker image uses mysql-community-server-minimal.
Therefore, Mroonga for AlamLinux 8 doesn't install on MySQL official Docker image in default.
Therefore, We need to create Mroonga package for Oracle Linux 8.
> groonga-release: add support for Oracle Linux 8

- Rakefile
- groonga-release/Rakefile
- groonga-release/yum/groonga-release.spec.in
- groonga-release/yum/oracle-linux-9/Dockerfile
- helper.rb
We need to merge https://github.com/groonga/packages.groonga.org/pull/33 before merging this PR.
> groonga-release: add support for Oracle Linux 9

- mecab-oracle-linux-8/.gitignore
- mecab-oracle-linux-8/Rakefile
- mecab-oracle-linux-8/yum/oracle-linux-8/Dockerfile
- mecab-oracle-linux-9/.gitignore
- mecab-oracle-linux-9/Rakefile
- mecab-oracle-linux-9/yum/oracle-linux-9/Dockerfile
Because we need to mecab-devel for Oracle Linux 8 and 9 to build the package of Groonga.
> mecab: support Oracle Linux 8 and 9

- groonga-apt-source/Rakefile
- groonga-apt-source/apt/debian-bookworm/Dockerfile
* Drop support for Debian 10 (buster)
* Add support for Debian 12 (bookworm)
> groonga-apt-source: refresh Debian support

- apache-arrow/Rakefile
CentOS 7's EOL came. So Groonga stopped supporting a package for CentOS 7.
ref: https://blog.centos.org/2023/04/end-dates-are-coming-for-centos-stream-8-and-centos-linux-7/
> apache arrow: drop support for CentOS 7

- apache-arrow/Rakefile
Apache Arrow 17.0.0 has released.
ref: https://arrow.apache.org/release/17.0.0.html
> apache arrow: update Apache Arrow to 17.0.0

- apache-arrow/README.md
We added the explanation about why we mirror Apache Arrow.
This context will help Groonga's maintainers to handle how to mirror Apache Arrow.
> apache arrow: add why we mirror Apache Arrow packages

- apache-arrow/Rakefile
Debian bullseye have already reached EOL.
> apache arrow: drop support for Debian bullseye

- ansible/files/home/deployer/webhook/lib/deployer/app.rb
- ansible/files/home/deployer/webhook/lib/deployer/response.rb
GitHub: GH-43
In this PR, we set up the authorization flow for webhook requests.
At the following PRs, we will implement the logic of deployments.
> release: authorize webhook request using webhook secret token

- ansible/files/home/deployer/webhook/lib/deployer/app.rb
- ansible/files/home/deployer/webhook/lib/deployer/error.rb
- ansible/files/home/deployer/webhook/lib/deployer/payload.rb
- ansible/files/home/deployer/webhook/lib/deployer/response.rb
GitHub: GH-43
In this PR, we set up how release flow is triggered from webhook
requests.
> release: trigger release processes when release workflow succeeded  

- ansible/files/home/packages/webhook/lib/deployer/app.rb
This PR is a part of automatically releasing signed packages.
- Add groonga-nginx's release flow to the deploy webhook in packages.groonga.org.
- Using release event triggers the webhook
> deploy webhook: add support for `groonga-nginx`

- ansible/files/home/packages/webhook/lib/deployer/app.rb
- ansible/files/home/packages/webhook/lib/deployer/payload.rb
GitHub: https://github.com/groonga/groonga/pull/2234
In our release workflow, we no longer use the
`workflow_run` event. Instead, we rely on the `release` event which is aligning our process with related
projects such as PGroonga and Mroonga.
This change removes all logic related to `workflow_run` events, simplifying the deployment process.
> deploy webhook: remove `workflow_run` event handling

- groonga-apt-source/Rakefile
Until now, groonga-apt-source packages were not provided via Launchpad.
We plan to migrate from the Launchpad PPA (ppa:groonga/ppa) to the Groonga APT repository (packages.groonga.org) due to certain limitations like we cannot use Groonga built with Apache Arrow enabled
This change enables support for groonga-apt-source packages on Ubuntu.
With this update, Launchpad users can easily register the Groonga APT repository and start using it.
> groonga-apt-source: support for Ubuntu packages in Launchpad

- groonga-apt-source/Rakefile
Running `rake ubuntu` command raised the following
error because we don't include `Helper::ApacheArrow` which provides `latest_commit_time`.
```console
$ rake ubuntu
rake aborted!
NoMethodError: undefined method 'latest_commit_time' for an instance of GroongaAptSourcePackageTask (NoMethodError)
latest_commit_time(File.join(__dir__, "..")))
^^^^^^^^^^^^^^^^^^
/home/otegami/work/ruby/packages.groonga.org/groonga-apt-source/Rakefile:9:in 'GroongaAptSourcePackageTask#initialize'
/home/otegami/work/ruby/packages.groonga.org/groonga-apt-source/Rakefile:123:in 'Class#new'
/home/otegami/work/ruby/packages.groonga.org/groonga-apt-source/Rakefile:123:in '<top (required)>'
(See full trace by running task with --trace)
```
Instead of using `latest_commit_time`, we now use
`detect_release_time` to get …
> groonga-apt-source: use detect_release_time in PackagesGroongaOrgPackageTask

- groonga-apt-source/Rakefile
Running `rake apt:build` failed as follows because the `github_repository` method was not defined in
`GroongaAptSourcePackageTask`.
By defining `github_repository`, the apt build process can now complete successfully.
```console
rake apt:build
rm -rf apt/tmp
mkdir -p apt/tmp
cp groonga-apt-source-2024.12.31.tar.gz apt/tmp/groonga-apt-source-2024.12.31.tar.gz
cp -r debian apt/tmp/debian.debian-bookworm
cp -r debian apt/tmp/debian.debian-trixie
cp -r debian apt/tmp/debian.ubuntu-jammy
cp -r debian apt/tmp/debian.ubuntu-noble
cd apt
rake aborted!
NotImplementedError: NotImplementedError (NotImplementedError)
/home/otegami/work/c/groonga/packages/packages-groonga-org-package-task.rb:136:in 'PackagesGroongaOrgPackageTask#github_repository' …
```
> groonga-apt-source: define missed github_repository for building apt packages

- groonga-apt-source/debian/rules
In Launchpad builds, building groonga-apt-source package failed as follows.
```
dpkg-buildpackage
-----------------
Command: dpkg-buildpackage --sanitize-env -us -uc -mLaunchpad Build Daemon <buildd@lcy02-amd64-094.buildd> -b -rfakeroot
dpkg-buildpackage: info: source package groonga-apt-source
dpkg-buildpackage: info: source version 2024.12.31-1.ubuntu22.04.1
dpkg-buildpackage: info: source distribution jammy
dpkg-source --before-build .
dpkg-buildpackage: info: host architecture amd64
fakeroot debian/rules clean
dh clean
dh_clean
debian/rules build
dh build
dh_update_autotools_config
dh_autoreconf
debian/rules override_dh_auto_build
make[1]: Entering directory '/<<PKGBUILDDIR>>'
gpg \
--no-default-keyring \
--keyring ./groonga-archive-keyring.kbx \
--import keys
gpg: keybox …
```
> groonga-apt-source: don't require home directory

- groonga-release/yum/groonga-release.spec.in
- helper.rb
GitHub: Fix GH-71
GitHub: ref https://github.com/groonga/groonga/pull/2528
This PR updates groonga-release for AlmaLinux 10 to drop the outdated/low-strength RPM GPG key.
It also ships only the RSA4096 key. It resolves the following error about the `dnf` GPG check failure reported.
```console
...
The Groonga Project for AlmaLinux 10 - x86_64                                                                          1.6 MB/s | 1.6 kB     00:00    
Importing GPG key 0x45499429:
Userid     : ""
Fingerprint: C97E 4649 A205 1D0C EA1A 73F9 72A7 496B 4549 9429
From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-45499429
error: Certificate 72A7496B45499429:
Policy rejects 72A7496B45499429: No binding signature at time 2025-09-24T09:35:25Z
Key import failed (code 2). Failing package is: …
```
> groonga-release: remove outdated GPG key for AlmaLinux10
